#!/bin/bash
yum -y install httpd
chkconfig httpd on
service httpd start
service iptables stop
f=/var/www/html/index.html
rm -f $f
echo "<html><head><title>Nepho built example system</title></head><body>" > $f
echo "<pre>System $(hostname) built on $(date).</pre>" >> $f
echo "</body></html>" >> $f
