VAGRANTFILE_API_VERSION = "2"

n_box_name    = ENV.fetch('NEPHO_BoxName',          'CentOS-6.4-x86_64')
n_box_url     = ENV.fetch('NEPHO_BoxUrl',           'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box')

n_guest_type  = ENV.fetch('NEPHO_GuestType',        'linux')
n_payload_dir = '/var/lib/nepho'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box_url = n_box_url
  config.vm.box     = n_box_name

  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Mount a shared folder containing the cloudlet's data files
  config.vm.synced_folder File.expand_path(File.join(File.dirname(__FILE__), "..", "..", "payload")), n_payload_dir 

  # Call Nepho provisioning scripts if they exist and are executable
  path = File.join(n_payload_dir, 'hooks', 'bootstrap')
  config.vm.provision :shell, :inline => \
    "[[ -x #{path} ]] && (echo Running #{path}; #{path})"

end
