VAGRANTFILE_API_VERSION = "2"

box      = 'centos6p5'
url      = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box'
ram      = '615'

$script = <<SCRIPT
yum -y install httpd
chkconfig httpd on
service httpd start
f=/var/www/html/index.html
rm -f $f
echo "<html><head><title>Vagrant built example system</title><body>" > $f
echo "<pre>System $(hostname) built on $(date).</pre>" >> $f
echo "</body></html>" >> $f
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box_url = url
  config.vm.box     = box

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder ".", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
    vb.customize [ 'modifyvm', :id, '--memory', ram]
  end

  config.vm.provision "shell", inline: $script

end
